### ISSUE TITLE
Did it work?

### ISSUE THREAD

**Issue by jalada** [jamesyale/lancache#1]
Hey,

Just wanted to find out if this config worked OK; there's not a lot of up-to-date copies of the configuration or information about hostnames to use etc. and this was the configuration with the most recent updated timestamp I could find :)

**Comment by jamesyale** [comment]
Hi, 

Yes, this is the working configuration we currently use at the BIG GAME LAN - (https://thebiggame.org). Believe the only configuration you'll need to add is to mount a device for the data at the mount point specified in the module, and then the normal LAN cache DNS entries (you've reminded me that I meant to add them to git too).

**Comment by jalada** [comment]
Thanks @jamesyale!
